### ISSUE TITLE
Invalid Podfile error...

### ISSUE THREAD

**Issue by sorka95032** [dlowder-salesforce/RNAppleTVTalk#1]
Following the install instructions, I get the following when I do the "pod install" from the root directory of the project.

 pod install
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:93: warning: Insecure world writable dir /sandbox in PATH, mode 040777

[!] Invalid `Podfile` file: cannot load such file -- /sandbox/gitrepos/RNAppleTVTalk-master/node_modules/react-native/scripts/autolink-ios.

 #  from /sandbox/gitrepos/RNAppleTVTalk-master/ios/Podfile:5
 #  -------------------------------------------
 #  
 >  require_relative '../node_modules/react-native/scripts/autolink-ios'
 #  
 #  -------------------------------------------

**Comment by douglowder** [comment]
Good catch! I’ll fix this tomorrow.....

**Comment by douglowder** [comment]
Just pushed the fix to master....
