### ISSUE TITLE
Unable to run. 

### ISSUE THREAD

**Issue by kosso** [dlowder-salesforce/RNAppleTVTalk#10]
Hello there,

I arrived at this repo as it it linked as the first sample demo from the [Wiki](https://github.com/react-native-tvos/react-native-tvos/wiki)

However, following the initial build instructions provided fails to work. 

The step `yarn run bundle_ios_dev` failed with `command not found: react-native` 

So, I installed the CLI with: `yarn add  @react-native-community/cli` 

The next attempt then failed with: `error: unknown command 'bundle'` 

I'm desperately trying to get up and running with developing a simple tvOS using RN, but I seem to be having a lot of issues with what appears to be quite out-of-date samples. 

Is there any chance at all of updating this sample (or any of them) to current versions please?

It might really help people like me to get past this initial roadblock/hurdle. 

Many thanks!

**Comment by douglowder** [comment]
@kosso I apologize -- the Wiki is in sore need of maintenance. I'll get that updated in the next few days. I will also take a crack at bringing this app back to life, it hasn't been maintained for a long time.

The quickest way to get up and running with a new RN app for TV today is this:

```
yarn create expo-app MyApp -e with-tv
```

Please see the following:

- Expo's blog post on building apps for TV: https://expo.dev/blog/how-to-build-tv-apps
- Our live stream on TV app development: https://www.youtube.com/watch?v=PUMBWeLVuiw
- Video example project (demo 1): https://github.com/douglowder/VideoTest
- Ignite example project (demo 2): https://github.com/react-native-tvos/IgniteTV
- TV API demo project (demo 3): https://github.com/react-native-tvos/TVInputDemo

**Comment by kosso** [comment]
@douglowder Thanks for getting back to me. 

I did eventually manage to get your `TVInputDemo` running after adding `@react-native-community/cli` to the devDependencies. It appears to be based on more recent dependencies. 

I'm currently looking to port [this music video site ](https://thisisamazing.com)I built (using Angular) over to AppleTV using React Native.  (When this URL is run on FireTV, AndroidTV or webOD/Tizen it also supports Spatial Navigation.)

I'm very new to React, but I think once I get past these initial hurdles with running examples and samples and learning from them, I hope to get well underway with the port. :)

**Comment by kosso** [comment]
By the way, I found that after running the `yarn create expo-app MyApp -e with-tv` command 

I first had to run 
```
export EXPO_TV=1
npx expo prebuild --clean
```

to make `yarn ios` work.

**Comment by douglowder** [comment]
@kosso that is correct, and is mentioned in the README :)

Also, I've now updated this repo to build with Expo. Pull the main branch and follow the updated instructions in the README.

I'm surprised that you needed to add the community CLI to TVInputDemo dependencies, as it should be picked up by react-native package automatically...
